tools:
  recompose:
    signature: recompose
    docstring: >
      A tool that needs to be called when a goal within the plan is completed.
      Notes for using the `recompose` command:
      * The `recompose` tool must be called when a goal within the plan is completed.
      * The tool must be called multiple times over the course of a task, as goals are completed.
    arguments: []
